function data = loadAnalogueIntanData(header, analogPath)
% Function to read in analog voltage data recorded on the intan
% Following is taken from RHD Application Note: Data File Formats - Intan Technologies
% https://intantech.com/files/Intan_RHD2000_data_file_formats.pdf
% Board ADC input data file: analogin.dat
% This file contains a matrix of ADC samples from the analog inputs on the USB interface board, in uint16 format. To convert to volts, multiply by 0.000050354. (If the board mode is not equal to zero, other scaling values may apply.)
% If no board ADC input channels are enabled in the GUI, this file will not be written.
% The following MATLAB code reads a board ADC input data file and creates a waveform matrix with units of volts:


num_channels = length(header.board_adc_channels); % ADC input info from header file
fileinfo = dir(analogPath);
num_samples = fileinfo.bytes/(num_channels * 2); % uint16 = 2 bytes
fid = fopen('analogin.dat', 'r');
data = fread(fid, [num_channels, num_samples], 'uint16');
fclose(fid);
% v = v * 0.000050354; % convert to volts
% If the data file was generated by an Intan Recording Controller, use the following scaling instead:
data = (data - 32768) * 0.0003125; % convert to volts (Recording Controller)